version: "3.2"
services: 
  elasticsearch:
    image: elasticsearch:7.8.1
    volumes:
      - /data:/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  # redis:
  #   image: redis:6.0.6
  #   volumes:
  #     - /data:/data
  #   ports:
  #     - "27017:27017"
          
  scylla:
    image: scylladb/scylla:4.3.0
    volumes:
      - /var/lib/scylla:/var/lib/scylla
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
      - "9180:9180"


  # reaper:
  #   image: thelastpickle/cassandra-reaper:latest
  #   environment:
  #     - REAPER_STORAGE=cassandra
  #     - REAPER_CASS_CONTACT_POINTS=["192.168.0.1"]
  #     - REAPER_CASS_KEYSPACE=reaper_db
  #     # - REAPER_CASS_CLUSTER_NAME=
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"


      